# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0ddd7e7829ac3a8f230b3ce7310849b8a4527e57ee0da04b42a238d7f574784232a70a133ba0f2888ce61018b8484723365f06784fbaf8d0508deb45a21ece

test:
  secret_key_base: e7b7e8dc2ce684b794981b9e3c44c107d1650728143455b5cbd0e3c0aa849f9348335cf54f5633d123c47b359f903981b26b6ac061d8f0a7ecb9b8add22a82b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
